[ITT-504] Regenerate all service
Adyen/adyen-ruby-api-library pull request #135
Opened 2023-05-04 10:49 UTC by jillingk

**Description**
Regenerate services, put classic payments in single class, adjust unit tests.

2023-05-04 13:08 UTC, wboereboom requested changes

2023-05-04 13:08 UTC, wboereboom commented on Makefile
> +
```suggestion
```

2023-05-04 13:08 UTC, wboereboom commented on lib/adyen-ruby-api-library.rb
> +require_relative "adyen/services/dataProtection.rb"
Why do we need the `.rb` for some imports, but not for others?

2023-05-04 13:17 UTC, jillingk commented on lib/adyen-ruby-api-library.rb
> +require_relative "adyen/services/dataProtection.rb"
We actually don't apparently.

2023-05-04 13:43 UTC, wboereboom approved these changes

2023-05-05 09:12 UTC, wboereboom approved these changes
Assuming we're doing the README in a separate PR

2023-05-05 12:13 UTC, wboereboom approved these changes

2023-05-05 12:18 UTC, AlexandrosMor approved these changes

2023-05-05 12:19 UTC, michaelpaul approved these changes

2023-05-05 12:29 UTC, merged