update makefile and readme to upgrade Transfers and Management API
Adyen/adyen-ruby-api-library pull request #162
Opened 2023-08-18 12:04 UTC by wboereboom

**Description**
This PR upgrades:
- Transfers service from v3 to v4
- Management service from v1 to v3

2023-08-18 12:17 UTC, michaelpaul approved these changes

2023-08-18 12:17 UTC, Aleffio approved these changes

2023-08-22 09:46 UTC, michaelpaul requested changes
WIP

2023-10-23 11:44 UTC, Aleffio commented
closing this as I opened a new one: https://github.com/Adyen/adyen-ruby-api-library/pull/189

2023-10-23 11:44 UTC, closed without merging